server {
    listen 80;
    server_name test.thejanv.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    location / {
        return 301 https://$host$request_uri\;
    }
}

server {
    listen 443 ssl;
    server_name test.thejanv.com www.test.thejanv.com;
    root /var/www/html;
    index index.php index.html;
    client_max_body_size 20M;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    ssl_certificate /etc/letsencrypt/live/test.thejanv.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/test.thejanv.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 120;
    }

    location ~ /\. {
        deny all;
    }
}
